### ISSUE TITLE
Uncomment the caching

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-marketing#1]
@tnavatar when you are back into making updates and testing can you uncomment the caching in the .htaccess and see if it still have issues.  Caching is needed for prod and okay to enable in dev 
https://github.com/clingen-data-model/clingen-marketing/commit/aa57f62f0b97db06b2d1f670f35dabbb4ab2b2c4

**Comment by sgoehringer** [comment]
@tnavatar I'm glad to uncomment but I didn't want to introduce it without you knowing.

**Comment by tnavatar** [comment]
Resolved
