### ISSUE TITLE
Configure regular backups

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/clingen-marketing#2]
Currently backups are manual only for the marketing website. Need to configure automated backups for the /data/processwire-assets folder, as well as regular database dumps for the pw db in MariaDB. A simple rsync to Google Cloud Storage will be sufficient for /data/processwire-assets for the first pass. The database dumps should, however, be maintained. Daily backups should be sufficient. Ideally backups would be stored in cloud storage in a location accessible for an automated restore.

**Comment by sgoehringer** [comment]
@tnavatar you may want to check with Phil but I believe this is all set.

**Comment by sgoehringer** [comment]
@plweller3 completed this task
Noted as cleanup
